name: Push

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy, rustfmt

      - name: cargo fmt
        run: cargo fmt --all -- --check
        shell: bash

      - name: cargo clippy
        run: cargo clippy -- -D clippy::all
        shell: bash

      - name: cargo build
        run: cargo build
        shell: bash

      - name: cargo test
        run: cargo test -- --nocapture
        shell: bash

      - name: cargo package
        run: cargo package
        shell: bash
